/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-python.h
 #	source generated by 4D Plugin Wizard
 #	Project : python
 #	author : miyako
 #	2021/11/17
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_PYTHON_H
#define PLUGIN_PYTHON_H

#include "4DPluginAPI.h"

#include "Python.h"

#if VERSIONMAC
#import <Cocoa/Cocoa.h>
#else
#define BZ_EXTERN
#endif

#define THIS_BUNDLE_ID @"com.4D.python"
#define THIS_BUNDLE_NAME L"python.4DX"

#include "json/json.h"

#pragma mark -

void python(PA_PluginParameters params);

#include "4DPlugin-JSON.h"

static void u16_to_u8(CUTF16String& u16, std::string& u8);
static void u8_to_u16(std::string& u8, CUTF16String& u16);

#endif /* PLUGIN_PYTHON_H */
